// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InventoryWidgetSource struct {
	Ids            []int              `json:"ids"`
	WidgetsByPrice *PriceWidgetSource `json:"widgetsByPrice"`
}

func (InventoryWidgetSource) IsEntity() {}

type PageInfo struct {
	TotalCount int `json:"totalCount"`
}

type PriceFilter struct {
	MinPrice *int `json:"minPrice"`
	MaxPrice *int `json:"maxPrice"`
}

type PriceWidgetSource struct {
	Ids     []int       `json:"ids"`
	Widgets *WidgetPage `json:"widgets"`
}

func (PriceWidgetSource) IsEntity() {}

type Widget struct {
	ID    int `json:"id"`
	Price int `json:"price"`
}

func (Widget) IsEntity() {}

type WidgetPage struct {
	Items    []*Widget `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type WidgetSource struct {
	Ids            []int              `json:"ids"`
	WidgetsByPrice *PriceWidgetSource `json:"widgetsByPrice"`
}

func (WidgetSource) IsEntity() {}
