// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InventoryFilter struct {
	MinInventory int `json:"minInventory"`
}

type InventoryWidgetSource struct {
	Ids     []int       `json:"ids"`
	Widgets *WidgetPage `json:"widgets"`
}

type PageInfo struct {
	TotalCount int `json:"totalCount"`
}

type PriceWidgetSource struct {
	Ids                []int                  `json:"ids"`
	WidgetsByInventory *InventoryWidgetSource `json:"widgetsByInventory"`
}

func (PriceWidgetSource) IsEntity() {}

type Widget struct {
	ID        int `json:"id"`
	Inventory int `json:"inventory"`
}

func (Widget) IsEntity() {}

type WidgetPage struct {
	Items    []*Widget `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type WidgetSource struct {
	Ids                []int                  `json:"ids"`
	WidgetsByInventory *InventoryWidgetSource `json:"widgetsByInventory"`
}

func (WidgetSource) IsEntity() {}
